language: python

python: 
        - 3.8
before_install:
        - python --version
        - pip install --upgrade pip
install:
        - pipenv install --system --deploy
after_install:
        - python -m unittest parser_controller
branches:
        only:
                - "main"
